stages:
- name: Build Image
  steps:
  - publishImageConfig:
      dockerfilePath: ./Dockerfile
      buildContext: .
      tag: ${CICD_GIT_REPO_NAME}:${CICD_EXECUTION_ID}
- name: Deploy App
  steps:
  - applyYamlConfig:
      path: ./K8S/deployment.pw-ziemba-net.yaml
  - applyYamlConfig:
      path: ./K8S/service.pw-ziemba-net.yaml
timeout: 60
notification: {}