apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: websites
  name: website-pw-ziemba-net
spec:
  replicas: 1
  selector:
    matchLabels:
      app: website-pw-ziemba-net
  minReadySeconds: 10
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: website-pw-ziemba-net
    spec:
      imagePullSecrets:
        - name: pipeline-docker-registry
      containers:
      - image: ${CICD_IMAGE}:${CICD_GIT_BRANCH}
        name: website-pw-ziemba-net
        ports:
        - containerPort: 80
